import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/redux/ReduxProvider";
import "@/services/setupInterceptors";

import BottomNavBar from "@/components/site/BottomNavBar";
import Header from "@/components/site/Header";
import SideBar from "@/components/site/SideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <SideBar />
        <ReduxProvider>{children}</ReduxProvider>
        <BottomNavBar />
      </body>
    </html>
  );
}
